Repository liupeirong/MLOpsManufacturing, pull requests merged in 2021-02, with the labels that each got.

#60 add observability docs
  docs/README.md
  docs/media/observability-choice.png
  docs/observability/MonitorAzureResources.md
Labels: documentation

#55 Added Function sample to monitor AML pipeline run results
  common/README.md
  common/pipeline_monitor/.flake8
  common/pipeline_monitor/README.md
  common/pipeline_monitor/devops_pipelines/code-quality-template.yml
  common/pipeline_monitor/devops_pipelines/monitor-functions-ci.yml
  common/pipeline_monitor/environment_setup/provisioning/README.md
  common/pipeline_monitor/environment_setup/provisioning/arm-templates/cloud-environment-functions.json
  common/pipeline_monitor/environment_setup/provisioning/iac-create-environment-functions-arm.yml
  common/pipeline_monitor/src/.funcignore
  common/pipeline_monitor/src/PipelineRunMonitor/__init__.py
  common/pipeline_monitor/src/PipelineRunMonitor/function.json
  common/pipeline_monitor/src/PipelineRunMonitor/pipeline_run_monitor.py
  common/pipeline_monitor/src/host.json
  common/pipeline_monitor/src/local.settings.json
  common/pipeline_monitor/src/local.settings.json.example
  common/pipeline_monitor/tests/src/PipelineRunMonitor/test_pipeline_run_monitor.py
Labels: documentation, enhancement

#56 Add variable examples
  docs/variable-management.md
Labels: documentation

#58 "Appendable Template" sample added
  samples/appendable-template/.env.example
  samples/appendable-template/README.md
  samples/appendable-template/diabetes_regression/.amlignore
  samples/appendable-template/diabetes_regression/ci_dependencies.yml
  samples/appendable-template/diabetes_regression/conda_dependencies.yml
  samples/appendable-template/diabetes_regression/evaluate/evaluate_model.py
  samples/appendable-template/diabetes_regression/parameters.json
  samples/appendable-template/diabetes_regression/register/register_model.py
  samples/appendable-template/diabetes_regression/training/test_train.py
  samples/appendable-template/diabetes_regression/training/train.py
  samples/appendable-template/diabetes_regression/training/train_aml.py
  samples/appendable-template/diabetes_regression/util/__init__.py
  samples/appendable-template/diabetes_regression/util/model_helper.py
  samples/appendable-template/environment_setup/install_requirements.sh
  samples/appendable-template/ml_service/__init__.py
  samples/appendable-template/ml_service/pipelines/__init__.py
  samples/appendable-template/ml_service/pipelines/diabetes_regression_build_train_pipeline.py
  samples/appendable-template/ml_service/pipelines/load_sample_data.py
  samples/appendable-template/ml_service/pipelines/steps/diabetes_regression_evaluate_step.py
  samples/appendable-template/ml_service/pipelines/steps/diabetes_regression_register_step.py
  samples/appendable-template/ml_service/pipelines/steps/diabetes_regression_train_step.py
  samples/appendable-template/ml_service/util/__init__.py
  samples/appendable-template/ml_service/util/attach_compute.py
  samples/appendable-template/ml_service/util/env_variables.py
  samples/appendable-template/ml_service/util/manage_environment.py
Labels: enhancement

#59 Unified logger for Azure ML, App Insights, and Console
  .gitignore
  common/azureml_appinsights_logger/LICENSE
  common/azureml_appinsights_logger/README.md
  common/azureml_appinsights_logger/azureml_appinsights_logger/__init__.py
  common/azureml_appinsights_logger/azureml_appinsights_logger/appinsights_logger.py
  common/azureml_appinsights_logger/azureml_appinsights_logger/azureml_logger.py
  common/azureml_appinsights_logger/azureml_appinsights_logger/console_logger.py
  common/azureml_appinsights_logger/azureml_appinsights_logger/env_variables.py
  common/azureml_appinsights_logger/azureml_appinsights_logger/logger_interface.py
  common/azureml_appinsights_logger/azureml_appinsights_logger/observability.py
  common/azureml_appinsights_logger/cd-pipeline.yml
  common/azureml_appinsights_logger/ci-pipeline.yml
  common/azureml_appinsights_logger/conda_dependency.yml
  common/azureml_appinsights_logger/media/logs-aml.png
  common/azureml_appinsights_logger/media/logs-appinsights.png
  common/azureml_appinsights_logger/media/metrics-appinsights.png
  common/azureml_appinsights_logger/media/metrics.png
  common/azureml_appinsights_logger/media/span-appinsights.png
  common/azureml_appinsights_logger/pyproject.toml
  common/azureml_appinsights_logger/sample/conda_dependency.yml
  common/azureml_appinsights_logger/sample/main.py
  common/azureml_appinsights_logger/sample/train.py
  common/azureml_appinsights_logger/setup.cfg
  common/azureml_appinsights_logger/tests/__init__.py
  common/azureml_appinsights_logger/tests/test_appinsights_logger.py
  common/azureml_appinsights_logger/tests/test_azureml_logger.py
  common/azureml_appinsights_logger/tests/test_console_logger.py
  common/azureml_appinsights_logger/tests/test_observability.py
Labels: enhancement

#57 AML SDK fixture Reamd update
  common/README.md
  common/pytest-fixtures/README.md
  common/pytest-fixtures/test_aml_mock_fixtures_default.py
  common/pytest-fixtures/test_aml_mock_fixtures_env.py
  samples/non-python-preprocess/devops_pipelines/01-pull-request.yml
  samples/non-python-preprocess/devops_pipelines/dependency-update-template.yml
  samples/non-python-preprocess/local_development/dev_dependencies.yml
  samples/non-python-preprocess/ml_service/tests/pipelines/test_aml_mock_fixtures_env.py
  samples/non-python-preprocess/ml_service/tests/pipelines/test_build_data_processing_os_cmd_pipeline.py
  samples/non-python-preprocess/ml_service/tests/pipelines/test_run_data_processing_pipeline.py
Labels: documentation, tooling
